### ISSUE TITLE
inconsistent module descriptor file

### ISSUE THREAD

**Issue by CBaci-CSS** [RealizeIdeas/grails-spring-social-instagram#2]
Loading Grails 2.2.5
| Configuring classpath
| Downloading: spring-social-instagram-0.1.pom.sha1
:: problems summary ::
:::: WARNINGS
        ::::::::::::::::::::::::::::::::::::::::::::::
        ::          UNRESOLVED DEPENDENCIES         ::
        ::::::::::::::::::::::::::::::::::::::::::::::
        :: #spring-social-instagram;0.1: java.text.ParseException: inconsistent module descriptor file found in 'http://grails.org/plugins/grails-spring-social-instagram/tags/RELEASE_0_1/spring-social-instagram-0.1.pom': bad organisation: expected='' found='org.grails.plugins'; 
        ::::::::::::::::::::::::::::::::::::::::::::::
:::: ERRORS
        grailsCentral: bad organisation found in http://grails.org/plugins/grails-spring-social-instagram/tags/RELEASE_0_1/spring-social-instagram-0.1.pom: expected='' found='org.grails.plugins'
| Downloading: spring-social-instagram-0.1.pom.sha1
:: problems summary ::
:::: WARNINGS
        ::::::::::::::::::::::::::::::::::::::::::::::
        ::          UNRESOLVED DEPENDENCIES         ::
        ::::::::::::::::::::::::::::::::::::::::::::::
        :: #spring-social-instagram;0.1: java.text.ParseException: inconsistent module descriptor file found in 'http://grails.org/plugins/grails-spring-social-instagram/tags/RELEASE_0_1/spring-social-instagram-0.1.pom': bad organisation: expected='' found='org.grails.plugins'; 
        ::::::::::::::::::::::::::::::::::::::::::::::
:::: ERRORS
        grailsCentral: bad organisation found in http://grails.org/plugins/grails-spring-social-instagram/tags/RELEASE_0_1/spring-social-instagram-0.1.pom: expected='' found='org.grails.plugins'

**Comment by MichaelAstreiko** [comment]
Do you have this repos in BuildConfig.groovy?
mavenRepo "http://maven.springframework.org/milestone/"
mavenRepo "http://maven.springframework.org/release/"
mavenRepo "http://maven.springframework.org/snapshot/"
mavenRepo "http://maven.springframework.org/milestone/"

**Comment by CBaci-CSS** [comment]
I do (BTW is there a duplicate in there?)

grails.servlet.version = "2.5" // Change depending on target container compliance (2.5 or 3.0)
grails.project.class.dir = "target/classes"
grails.project.test.class.dir = "target/test-classes"
grails.project.test.reports.dir = "target/test-reports"
grails.project.target.level = 1.6
grails.project.source.level = 1.6
//grails.project.war.file = "target/${appName}-${appVersion}.war"

// uncomment (and adjust settings) to fork the JVM to isolate classpaths
//grails.project.fork = [
//   run: [maxMemory:1024, minMemory:64, debug:false, maxPerm:256]
//

grails.project.dependency.resolution = {
    // inherit Grails' default dependencies
    inherits("global") {
        // specify dependency exclusions here; for example, uncomment this to disable ehcache:
        // excludes 'ehcache'
    }
    log "warn" // log level of Ivy resolver, either 'error', 'warn', 'info', 'debug' or 'verbose'
    checksums true // Whether to verify checksums on resolve
    legacyResolve false // whether to do a secondary resolve on plugin installation, not advised and here for backwards compatibility

```
repositories {
    inherits true // Whether to inherit repository definitions from plugins

    grailsPlugins()
    grailsHome()
    grailsCentral()

    mavenLocal()
    mavenCentral()

    // uncomment these (or add new ones) to enable remote dependency resolution from public Maven repositories
    //mavenRepo "http://snapshots.repository.codehaus.org"
    mavenRepo "http://repository.codehaus.org"
    //mavenRepo "http://download.java.net/maven/2/"
    //mavenRepo "http://repository.jboss.com/maven2/"
    //mavenRepo "http://repo.spring.io/milestone/"
        mavenRepo "http://maven.springframework.org/milestone/"
        mavenRepo "http://maven.springframework.org/release/"
        mavenRepo "http://maven.springframework.org/snapshot/"
        mavenRepo "http://maven.springframework.org/milestone/"
}

dependencies {
    // specify dependencies here under either 'build', 'compile', 'runtime', 'test' or 'provided' scopes e.g.
    // runtime 'mysql:mysql-connector-java:5.1.22'
    compile "javax.portlet:portlet-api:2.0"
    //compile ":spring-social-instagram:0.1"
}

plugins {
    runtime ":hibernate:$grailsVersion"
    runtime ":jquery:1.8.3"
    runtime ":resources:1.2.6"

    // Uncomment these (or add new ones) to enable additional resources capabilities
    //runtime ":zipped-resources:1.0"
    //runtime ":cached-resources:1.0"
    //runtime ":yui-minify-resources:0.1.5"

    build ":tomcat:$grailsVersion"

    //runtime ":database-migration:1.3.8"

    compile ':cache:1.1.1'
    compile ":spring-security-core:2.0-RC2"
    compile ":spring-security-oauth2-provider:1.0.5.2"
    compile ":portlets:0.9.2"
    compile ":portlets-liferay:0.4"
}
```

}

**Comment by MichaelAstreiko** [comment]
You should put 
compile ":spring-social-instagram:0.1"

into plugins section - not to dependencies

**Comment by CBaci-CSS** [comment]
_facepalm_ Thanks. Trying to make a liferay portlet to pull instagram images. Not sure to what level I need oauth.

**Comment by CBaci-CSS** [comment]
Thanks for your assistance!
now compile errors, could I have conficts b/c 
        compile ":spring-security-core:2.0-RC2"
        compile ":spring-security-oauth2-provider:1.0.5.2"
in my plugins?

**Comment by MichaelAstreiko** [comment]
It is a question. But I do not think you need spring-security-oauth2-provider at all. It contains logic to implement OAuth provider like your app is Facebook.
